on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: pushd Lodash.Net && dotnet build --configuration Release && popd
      - name: Test
        run: dotnet test -r ./.test_results --verbosity minimal --logger "trx;logfilename=results.trx"
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Unit Tests
          path: .test_results/results.trx
          reporter: dotnet-trx
